/**
 * One-time data migration for Option A (random ticket-number allocation).
 *
 * FULL WIPE (authorised): for EVERY non-deleted competition —
 *   - delete WinnerDetail rows      (draw results detail)
 *   - delete Result rows            (winners)
 *   - delete InstantWin rows        (old sequential picks; regenerated by cron)
 *   - delete Ticket rows            (old sequential numbers)
 *   - delete TicketReservation rows (in-flight holds)
 *   - reset soldTickets = 0, reservedTickets = 0, instantWinGenerated = false
 *   - set a shuffleKey if missing
 *
 * Deletion order respects FK chain:
 *   WinnerDetail -> Result -> (InstantWin, Ticket) -> Ticket -> Reservation.
 *
 * Safety:
 *   - DRY_RUN=true (default) only REPORTS what would change; it deletes nothing.
 *   - Run for real with:  DRY_RUN=false node scripts/migrateRandomTickets.js
 */

const crypto = require("crypto");
const prisma = require("../src/prismaconfig");

const DRY_RUN = process.env.DRY_RUN !== "false"; // default true (safe)

async function main() {
  console.log(`\n=== Random ticket migration (FULL WIPE) — ${DRY_RUN ? "DRY RUN (no changes)" : "LIVE RUN"} ===\n`);

  const comps = await prisma.competition.findMany({
    where: { deletedAt: null },
    select: { id: true, title: true, soldTickets: true, shuffleKey: true },
    orderBy: { id: "asc" },
  });

  console.log(`Competitions to process: ${comps.length}\n`);

  const totals = { tickets: 0, instantWins: 0, results: 0, winnerDetails: 0, reservations: 0, keysAdded: 0 };

  for (const c of comps) {
    const [tickets, instantWins, results, winnerDetails, reservations] = await Promise.all([
      prisma.ticket.count({ where: { competitionId: c.id } }),
      prisma.instantWin.count({ where: { competitionId: c.id } }),
      prisma.result.count({ where: { competitionId: c.id } }),
      prisma.winnerDetail.count({ where: { competitionId: c.id } }),
      prisma.ticketReservation.count({ where: { competitionId: c.id } }),
    ]);

    totals.tickets += tickets;
    totals.instantWins += instantWins;
    totals.results += results;
    totals.winnerDetails += winnerDetails;
    totals.reservations += reservations;
    if (!c.shuffleKey) totals.keysAdded += 1;

    console.log(
      `#${c.id} "${c.title}" — tickets:${tickets} instantWins:${instantWins} winners:${results} winnerDetails:${winnerDetails} reservations:${reservations} sold:${c.soldTickets} key:${c.shuffleKey ? "yes" : "NEW"}`
    );

    if (DRY_RUN) continue;

    await prisma.$transaction(async (tx) => {
      await tx.winnerDetail.deleteMany({ where: { competitionId: c.id } });
      await tx.result.deleteMany({ where: { competitionId: c.id } });
      await tx.instantWin.deleteMany({ where: { competitionId: c.id } });
      await tx.ticket.deleteMany({ where: { competitionId: c.id } });
      await tx.ticketReservation.deleteMany({ where: { competitionId: c.id } });
      await tx.competition.update({
        where: { id: c.id },
        data: {
          soldTickets: 0,
          reservedTickets: 0,
          instantWinGenerated: false,
          shuffleKey: c.shuffleKey || crypto.randomBytes(16).toString("hex"),
        },
      });
    });
  }

  console.log(`\n--- Summary (${DRY_RUN ? "would delete" : "deleted"}) ---`);
  console.log(`Tickets:        ${totals.tickets}`);
  console.log(`InstantWins:    ${totals.instantWins}`);
  console.log(`Winners:        ${totals.results}`);
  console.log(`WinnerDetails:  ${totals.winnerDetails}`);
  console.log(`Reservations:   ${totals.reservations}`);
  console.log(`shuffleKeys ${DRY_RUN ? "to add" : "added"}: ${totals.keysAdded}`);
  console.log(DRY_RUN ? "\nDRY RUN — nothing changed. Re-run with DRY_RUN=false to apply.\n" : "\nDone.\n");
}

main()
  .catch((e) => {
    console.error("Migration failed:", e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
